name: CICD

on:
  workflow_dispatch: # запуск вручную через GitHub UI
  push:              # или при пуше в репозиторий
  pull_request:

jobs:
  call-tests:
    uses: ./.github/workflows/test.yml

  name: CICD

on:
  workflow_dispatch:
  push:
  pull_request:  # <--- Добавим запуск на PR

jobs:
  call-tests:
    uses: ./.github/workflows/test.yml

  add-label:
    name: Add label to PR
    needs: call-tests # Разрешаем при успешном прохождении тестов 
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write #Даем права на запись 
    steps:
      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: test-passed

