name: CICD

on:
  workflow_dispatch: # запуск вручную через GitHub UI
  push:              # или при пуше в репозиторий
  pull_request:




env:
  NAME_VERSION_FILE: ${{ github.workspace }}/version/version
  RELEASE: release
  MINOR: minor
  PATCH: patch
  VERSION_UP: .github/workflows/version_update.py
  REPO_NAME: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ github.event.number }}
  URL_REPO: ${{ github.server_url }}/${{ github.repository }}
  CHANGELOG_FILE: changelog.md



jobs:
  call-tests:
    uses: ./.github/workflows/test.yml

  call-antivirus:
    needs: call-tests
    uses: ./.github/workflows/security.yml

  add-label:
    name: Add label to PR
    needs: call-tests # Разрешаем при успешном прохождении тестов 
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write #Даем права на запись 
    steps:
      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: test-passed
    

  validate_branch:  
    needs: security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code #Клонирование репозитория на виртуалку
        uses: actions/checkout@v2

      - name: Parse branch name
        id: parse-data # парсим имя ветки :)
        uses: tj-actions/branch-names@v8


