name: Tests

on:
  workflow_call #Тест вызываеться другим yml файлом (ci_cd.yml)

jobs:
  Test-1:
    name: Test-1
    runs-on: self-hosted
    steps:
      - name: Run test
        run: |
          echo "First test run"
  Test-2:
    name: Test-2
    runs-on: self-hosted
    steps:
      - name: Run test
        run: |
          echo "Second test run"

  add-label:
    name: Add label to PR
    needs: call-tests # Разрешаем при успешном прохождении тестов 
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: self-hosted
    permissions:
      pull-requests: write #Даем права на запись 
    steps:
      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: test-passed

